htwg-syslab/nix-expressions

shells/default.nix

Passt das so?
Wie wäre es noch einem eigenen Paket 'admin', in den so extra Zeugs von Admins (zsh und Co) reinkommt?

Adding some basics and geany Editor

---

shells/mkShellDerivation.nix

shells: add locale pkg and set en_US.UTF-8

---

shells/default.nix

shells/rust: set RUST_SRC_PATH in env

---

shells/default.nix

Mm psutils clang

---

shells/default.nix

shells/base: add strace

---

shells/default.nix

shells: set PAGER=less

---

.travis.yml
default.nix
shells/default.nix

shells: add rtos

---

shells/default.nix

Fixes https://github.com/htwg-syslab-syso/syso-ss17-homework/issues/8.

shells/sysoHW1: add code and rust dependencies

---

shells/default.nix

Fixes https://github.com/htwg-syslab-syso/syso-ss17-grp11/issues/2.

shells/sysoHW0: add base and code dependencies

---

shells/default.nix
shells/mkShellDerivation.nix

shells/base: use gitFull and enbale bashCompletion

---

shells/default.nix

shells/base: set git merge.tool if not set

---

.travis.yml
default.nix
scripts/labshell.sh
shells/default.nix

Fixes #36 
Fixes #35 
Fixes #13 
Fixes #63 
TODO

use rust-overlay for rust compiler+src, and cargo for crates

---

shells/default.nix

shells/base: set MANPATH

---

shells/default.nix

shells: generate MANPATH for all packages

---

shells/default.nix

shells/default: fix formatting

---

pkgs/labshell/src/labshell.sh
shells/default.nix

labshell & shells: increase debug information; refactor shell expressions; prefer native binaries in cross-development shells

---

shells/default.nix

I manually tested sysoHW[1-3] after refactoring

shells: add sysoHW4

---

shells/default.nix

* add rust variant choice and include rls as extension for nightly
* add rtosNightly with rust nightly which now includes rls
* add rls to stable rust
* split up rust deps

shells/rust: add nightly channel

---

default.nix
shells/default.nix

shells/rust: pin nightly to 2017-05-16

---

ci/complete.sh
shells/default.nix

shells/osdev: use grub2 and add util-linux

---

default.nix
pkgs/labshell/default.nix
shells/default.nix

bump nixpkgs; bump nixpkgs-mozilla; bump rust crates; bump rust nightly

---

shells/default.nix

shells: add ccache (code) and postgresql (webdev)

---

ci/test.sh
shells/default.nix

Fixes #112.
Fixes #113.
Fixes #69.
Fixes #107.

shells: fix manpath behavior and add common manpages

---

default.nix
pkgs/default.nix
pkgs/labshell/src/labshell.sh
shells/default.nix
shells/mkShellDerivation.nix

Fixes #111.
Closes https://github.com/htwg-syslab-syso/syso-ws17-homework/issues/7.

allow separate nixpkgs per flavor; fix the aarch64 crosspkgs; change crosspkgs handling
